theme: jekyll-theme-minimal
title: Milo Stickle-Frizzell
description: I’m a developer and artist living in Anchorage, AK, currently attending University of Alaska Anchorage. This website hosts projects I've worked on as a student. Check them out!
